version: "2.6.1"
services:
  database:
    container_name: mariadb
    image: mariadb
    volumes:
      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - MARIADB_DATABASE=test
      - MARIADB_ROOT_PASSWORD=test
      - MARIADB_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3000:3306

  application:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/test?useUnicode=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test
    ports:
      - 7777:7777
    depends_on:
      - mariadb