spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/test
    username: root
    password: test
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
server:
  port: 7777
logging:
  level:
    me.silvernine: debug
